/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

/**
 *
 * @author ACER
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form frameUtama
     */
    public frameUtama() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFormAdmin = new javax.swing.JButton();
        btnFormDaftar = new javax.swing.JButton();
        btnFormDokter = new javax.swing.JButton();
        btnFormKontak = new javax.swing.JButton();
        btnFormNews = new javax.swing.JButton();
        btnFormPerawatan = new javax.swing.JButton();
        btnFormSpesialis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFormAdmin.setText("Form Admin");
        btnFormAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormAdminActionPerformed(evt);
            }
        });

        btnFormDaftar.setText("Form Daftar");
        btnFormDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormDaftarActionPerformed(evt);
            }
        });

        btnFormDokter.setText("Form Dokter");
        btnFormDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormDokterActionPerformed(evt);
            }
        });

        btnFormKontak.setText("Form Kontak");
        btnFormKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormKontakActionPerformed(evt);
            }
        });

        btnFormNews.setText("Form News");
        btnFormNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormNewsActionPerformed(evt);
            }
        });

        btnFormPerawatan.setText("Form Perawatan");
        btnFormPerawatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPerawatanActionPerformed(evt);
            }
        });

        btnFormSpesialis.setText("Form Spesialis");
        btnFormSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormSpesialisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFormKontak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormNews, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormPerawatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormSpesialis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnFormAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnFormDaftar)
                .addGap(18, 18, 18)
                .addComponent(btnFormDokter)
                .addGap(18, 18, 18)
                .addComponent(btnFormKontak)
                .addGap(18, 18, 18)
                .addComponent(btnFormNews)
                .addGap(18, 18, 18)
                .addComponent(btnFormPerawatan)
                .addGap(18, 18, 18)
                .addComponent(btnFormSpesialis)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormAdminActionPerformed
        // TODO add your handling code here:
        new frameAdmin().setVisible(true);       
    }//GEN-LAST:event_btnFormAdminActionPerformed

    private void btnFormDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormDaftarActionPerformed
        // TODO add your handling code here:
        new frameDaftar().setVisible(true);
    }//GEN-LAST:event_btnFormDaftarActionPerformed

    private void btnFormDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormDokterActionPerformed
        // TODO add your handling code here:
        new frameDokter().setVisible(true);
    }//GEN-LAST:event_btnFormDokterActionPerformed

    private void btnFormKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormKontakActionPerformed
        // TODO add your handling code here:
        new frameKontak().setVisible(true);
    }//GEN-LAST:event_btnFormKontakActionPerformed

    private void btnFormNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormNewsActionPerformed
        // TODO add your handling code here:
        new frameNews().setVisible(true);
    }//GEN-LAST:event_btnFormNewsActionPerformed

    private void btnFormPerawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPerawatanActionPerformed
        // TODO add your handling code here:
        new framePerawatan().setVisible(true);
    }//GEN-LAST:event_btnFormPerawatanActionPerformed

    private void btnFormSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormSpesialisActionPerformed
        // TODO add your handling code here:
        new frameSpesialis().setVisible(true);
    }//GEN-LAST:event_btnFormSpesialisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormAdmin;
    private javax.swing.JButton btnFormDaftar;
    private javax.swing.JButton btnFormDokter;
    private javax.swing.JButton btnFormKontak;
    private javax.swing.JButton btnFormNews;
    private javax.swing.JButton btnFormPerawatan;
    private javax.swing.JButton btnFormSpesialis;
    // End of variables declaration//GEN-END:variables
}
